#+STARTUP: latexpreview
#+STARTUP: indent



* RECIPES
:PROPERTIES:
:CATEGORY: Recipes
:END:
** Dutch Oven/Braising
*** [[http://www.gourmettraveller.com.au/recipes/recipe-search/feature-recipe/2007/9/baeckeoffe/][Baeckoffe]]
*** [[http://www.foodnetwork.com/recipes/beef-bourguignonne-recipe][Beef Bourguignonne]]
*** [[http://www.foodnetwork.com/recipes/tyler-florence/chicken-marsala-recipe][Marsala Chicken]]
This is a chicken cutlet that has been flattened and can be quickly cooked in a pan. It is served with a wine based pan sauce and sauce and some vegetables

Ingredients:
4 boneless chicken breasts
All-purpose flour
Kosher salt and fresh ground pepper
1/4 cup extra-virgin olive oil
4 ounces proscuitto
8 ounces crimini or porcini mushrooms, stemmed and halved
1/2 cup sweet Marsala wine
1/2 cup chicken stock
2 tablespoon unsalted butter
1/4 cup chopped flat-leaf parsley


METHOD:
1. Lay the chicken breasts side-by-side and cover with plastic wrap. Pound the meat with some sort of primitive tool (or the flat side of a meat hammer if you have one) until 1/4-inch thick. Put some flour in a shallow platter and season  with salt and pepper.
2. Heat the oil over medium heat in a large skillet. Dredge both sides of the chicken in the flour and shake off excess. Put the cutlets in the pan for 5 minutes on each side. Remove from pan.
3. Lower the heat and add the proscuitto to the drippings in the pan, saute for 1 min to render some of the fat. Add mushrooms and saute untill they are nicely browned, about 5 minutes.
4. Pour Marsala in the pan and boil down for a few seconds, add the chicken stock and simmer for a minute. Stir in the butter and return the chicken to the pan. Serve.
*** [[https://smittenkitchen.com/2006/12/magnificence-au-vin/][coq au vin]]
** Pan/Quick Searing
*** [[https://www.nigella.com/recipes/mirin-glazed-salmon][Mirin Gl
azed Salmon]]

    INGREDIENTS
    60 ml mirin
    50 g brown sugar
    60 ml soy sauce
    500 gm salmon
    2 tablespoons rice wine vinegar
    1-2 spring onions (halved and shredded into fine strips)

    METHOD
    1. Mix the mirin, brown sugar and soy sauce in a shallow dish that
       will take all 4 pieces of salmon, and marinate the salmon in it
       for 3 minutes on the first side and 2 minutes on the
       second. Meanwhile heat a large non-stick frying pan on the hob.
    2. Cook the salmon in the hot, dry pan for 2 minutes and then turn
       the salmon over, add the marinade and cook for another 2
       minutes.
    3. Remove the salmon to whatever plate you're serving it on, add
       the rice vinegar to the hot pan, and warm through.
    4. Pour the dark, sweet, salty glaze over the salmon and top with
       the spring onion strips.
    5. Serve with rice or noodles as you wish, and consider putting
       some sushi ginger on the table, too.

*** [[http://www.bonappetit.com/recipe/stir-fried-udon-with-pork][Udon Pork Stirfry]]

    INGREDIENTS

    - 2 tablespoons vegetable oil
    - 4 cups of coursely chopped green cabbage
    - 2 packages of udon noodles
    - 2 teaspoons of sesame oil
    - 8 ounches of ground pork
    - 5 scallions
    - 2 teaspoons finely grated ginger
    - 1 teaspoon crushed red pepper
    - 1/3 cup mirin
    - 1/3 cup soy sauce
    - 1 tablespoon toasted sesame seeds

      1. Heat 1 Tbsp. vegetable oil in a large skillet over
        medium-high. Add cabbage and cook, tossing often, until edges
        are browned, about 4 minutes. Reduce heat to low and continue
        to cook, tossing often, until thickest parts of cabbage leaves
        are tender, about 4 minutes longer. Remove from heat and set
        skillet aside.

      2. Place udon in a large heatproof bowl (or pot if you don’t
         have one) and cover with 6 cups boiling water. Let sit 1
         minute, stirring to break up noodles, then drain in a
         colander. Transfer noodles back to bowl and toss with sesame
         oil. Transfer cabbage to bowl with noodles. Wipe out skillet.

      3. Heat remaining 1 Tbsp. vegetable oil in same skillet over
         medium-high and add pork, breaking up and spreading across
         surface of pan with a spatula or tongs. Cook pork,
         undisturbed, until underside is brown, about 3 minutes. The
         pork will never brown if you’re fussing with it the whole
         time, so when we say “undisturbed,” that means keep your paws
         off it and let the heat of the pan and the pork do their
         thing. When pork is browned, break up meat into small
         bits. Cook, tossing, just until there’s no more pink, about 1
         minute. Add chopped scallions (the pale parts), ginger, and
         red pepper. Continue to cook, tossing often, until scallions
         are softened and bottom of skillet has started to brown,
         about 1 minute. Add udon mixture, mirin, and soy sauce and
         cook, tossing constantly, until noodles are coated in sauce
         (be sure to scrape bottom of skillet to dissolve any browned
         bits), about 45 seconds. Remove from heat and fold in 1
         Tbsp. sesame seeds and dark-green parts of scallions. Top
         with more sesame seeds before serving.


* Emacs
** Toggle GUI Elements
   | menu-bar-mode   | toggles the top menu bar |
   | scroll-bar-mode | toggle the scroll bar    |
** Clocking Time

while cursor is on a TODO item:
    C-c C-x C-i  - to start time
    C-c C-x C-o  - to stop time
    C-c C-x C-r  - create a report table of the time stamps  

** Python

1. Set up the virtual environment in emacs
   M-x pyvenv-activate
   it will then prompt for file location, provide the path to the venv folder.
   Run python with: M-x run-python


* SYSTEMS LOG
** <2017-03-22 Wed> Started using org-indent-mode to indent heading
** <2017-03-23 Thu> Activated telnet for use through cmd (amdin)
activted with: dism /online /Enable-Feature /FeatureName:TelnetClient
seen on this [[https://www.rootusers.com/how-to-enable-the-telnet-client-in-windows-10/][site]]

* ffmpeg - Audio Conversion

To convert only the audio portion of a video fro ac3 (for use with the tv) use
ffmpg.exe -i Path\to\video.mkv -c:v copy -c:a ac3 Path\to\output-video.mvk

* TELNET
** Use SMTP to send an email
openssl s_client -starttls smtp -connect smtp.gmail.com:587 -crlf -ign_eof
ehlo localhost
auth login
# encoded username
bmVhbGUud2lsa2Vu
# encoded password
UGV0cm9uMQ==
# at this point you should be fully authorized
# now you send the mail
MAIL FROM: <neale.wilken@gmail.com>
rcpt to: <neale.wilken@gmail.com>
DATA
now you send the message
you can send another thing on other lines
# end the message with a .
.
QUIT

You can convert test to base64 with python package

import base64
base64.b64encode(bytes("put your text here","utf-8"))

* PYTHON
** Virtual Env Installation
install a new virtual environment with:
C:\Python35\python.exe -m venv c:\path\to\venv

The installer does not automatically create base folder before installation, so remeber to create a venv folder and specify it as the installation path.


** Installing from package
To install from a packge that you already downloaded, use:

> 
pip install path/to/package.whl
* GIT

** GIT Commands
|------------+----------------------------------------|
| git status | show the current status of the project |
| git branch | show the available branches            |
|            |                                        |
|------------+----------------------------------------|

** Save local changes to master
1. cd into project directory
2. git branch branchname
3. git checkout brachname
4. git add -A
5. git commit -am "this is where you put a note"
6. git checkout master
7. git merge branchname
8. cd back into the main production folder
9. git pull /path/to/project/branch
10. git push heroku master


* Heroku
|--------------------------------------+-------------------------------------------------------|
| heroku login                         | Username: neale.wilken@gmail.com, Password: Nxxxxxxx  |
| heroku create                        | Creates an app on heroku (not django app)             |
| git push heroku master               | push lastest changes to the remote machine            |
|--------------------------------------+-------------------------------------------------------|
| heroku ps:scale web=1                | activate a dyno for the web process- start the append |
| heroku ps:scale web=0                | stops the web app dyno                                |
| heroku open                          | opens  the browser to the web app                     |
|--------------------------------------+-------------------------------------------------------|
| heroku logs -tail                    | displays the tail of the server logs                  |
| heroku ps -check                     | check how many dynos are running                      |
|--------------------------------------+-------------------------------------------------------|
| heroku local web -f Procfile.windows | starts the app on the local machine                   |
| heroku git:clone -a appname          | create a clone of a heroku app                        |
|--------------------------------------+-------------------------------------------------------|

*** Deploy Process
1. git add .
2. git commit -m "demo"
3. git push heroku master
*** Rename
 an app
1. cd to the directory of the app to be renamed
2. heroku apps:rename newname

* POSTGRES

** POSTGRES Command line tool

You need to cd to the location of the psql tool since it is not in path

cd C:\Program Files\PostgreSQL\9.6\bin

Connect to the db

.\psql -d localdb -U postgres

Password: foomanchoo

Make sure you end SQL statements with ';' or they won't execute

| psql -d databasename -U username | connect to a database |
|----------------------------------+-----------------------|
| \dt                              | show all tables       |
| \x                               | toggles extended view |
|                                  |                       |

** Copy Heroku database to localdb

1. Create and download a backup of the heroku database:

heroku pg:backups:capture
heroku pg:backups:download

2. Restore the backup to the local database with:

pg_restore --verbose --clean --no-acl --no-owner -h localhost -U postgres -d locabdb latest.dump

Where the username: postgres and the local database name is: localdb
The downloaded backup of the heroku database is called lastest.dump

The command "pg_restore" may not be in the path, in which case it will not work.
The executable can be found in C:\Program Files\PostgreSQL\9.6\bin. Either add it to the path or use the full reference.
* Django

|----------------------------------+-----------------------------------------------------------|
| python manage.py startapp polls  | Create new app, in this case called polls                 |
| python manage.py createsuperuser | Creates a new admin user, mine is: U: nwilken P: Nxxxxxxx |
|----------------------------------+-----------------------------------------------------------|

* Machine Learning

- LogisticClassifier :: applies a linear function (which in this sence is a matrix multiplier) to an input, to determine a classification for the input. Can be represented which 
\(WX+b 
- Multinomial Logistic Classification :: Input -> Logit -> softmax -> 1-hot encoding
- Regularization :: when training a model, sometimes the weight parameters can grow very large. To combat this, we can use regularization, which penalizes large values in the weight to promote a smaller size weight. This helps reduces overfitting to the training data, and allows the model to perform better when handling new data.
-  :: 
